# Generated by Django 3.1.2 on 2020-10-03 13:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='chat.role', verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username_color',
            field=models.CharField(default='000000', help_text='Username color in chat, hex format.', max_length=6, validators=[django.core.validators.RegexValidator('^(?:[0-9a-fA-F]{3}){2}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='watchtime',
            field=models.PositiveIntegerField(default=0, help_text='Total time of the watched broadcasts (seconds).'),
        ),
    ]
