# Generated by Django 3.1.2 on 2020-11-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='sid',
            field=models.CharField(choices=[('user', 'User'), ('vip', 'VIP'), ('moderator', 'Moderator'), ('administrator', 'Administrator'), ('streamer', 'Streamer')], max_length=20, unique=True),
        ),
    ]
