# Generated by Django 3.1.2 on 2020-10-13 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201003_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Creation date.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date of last update.')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('source_link', models.URLField(help_text='Link to broadcast source.', verbose_name='source link')),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='streamer')),
            ],
            options={
                'verbose_name': 'broadcast',
                'verbose_name_plural': 'broadcasts',
                'db_table': 'broadcasts',
            },
        ),
    ]
