# Generated by Django 3.1.2 on 2020-10-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20201014_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='watchers_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of users that watch the broadcast.'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether broadcast is active now.'),
        ),
    ]
