# Generated by Django 3.1.7 on 2021-03-16 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('type', models.CharField(choices=[('smiley', 'Smiley'), ('icon', 'Icon'), ('badge', 'Badge'), ('custom', 'Custom')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chat.role')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_images',
            field=models.ManyToManyField(related_name='custom_owners', to='chat.Image'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.image'),
        ),
    ]
