# Generated by Django 3.1.7 on 2021-03-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210317_1611'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='broadcast',
            name='broadcasts_created_c465e9_idx',
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['created', 'is_active'], name='broadcasts_created_a36523_idx'),
        ),
    ]
