# Generated by Django 3.1.7 on 2021-03-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210317_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='source_link',
        ),
    ]
