name: Tests

on:
    push:
        branches:
            - dev

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.6

            - name: Start compose
              run: docker-compose up -d

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run tests
              working-directory: ./chatup
              run: python manage.py test --noinput --parallel
