name: Tests

on:
    push:
        branches:
            - dev

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - name: Start compose
              run: |
                  docker-compose up -d

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run tests
              working-directory: ./chatup
              env:
                  CUP_CONF: config_ci_tests.ini
              run: |
                  python manage.py test --noinput --parallel

    version:
        needs: tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Set version
              working-directory: ./chatup/config
              run: |
                  echo __version__ = $(git rev-list HEAD --count) > __init__.py
